[env]
  TERM = "xterm-256color"

[cursor.style]
shape = "Underline"

[window]
  opacity = 0.8

[font]
family = "JetbrainsMono NF Regular"
size = 9

[general]
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[window.padding]
x = 20
y = 20
