#!/usr/bin/bash

# ANSI color codes
R='\033[0;31m'  
G='\033[0;32m'  
Y='\033[1;32m'  
B='\033[0;34m'  
NC='\033[0m' 

pause() {
  printf "${Y} Press any key to continue${NC}"
  read -n 1 -s -r  
  printf "\r"
}

printf "${R}# Hello there, looks like you want to yoink my dots. :D ${NC}\n"
sleep 2

# Select AUR helper using whiptail
whiptail --title "Select AUR Helper" --yes-button "paru" --no-button "yay" --yesno "Choose your AUR helper" 10 50 3>&1 1>&2 2>&3
if [ $? -eq 0 ]; then
    HELPER="paru"
else
    HELPER="yay"
fi
echo "Selected AUR helper: $HELPER"

set -e
# Update system
printf "${R}# Updating your system (sudo pacman -Syu)${NC}\n"
sudo pacman --noconfirm -Syu
pause

# Install libnewt
printf "${R}# Installing libnewt on your system${NC}\n"
sudo pacman -S --noconfirm libnewt
pause

# Install base packages
printf "${R}# Installing base packages (base-devel, wget, git)${NC}\n"
sudo pacman --noconfirm --needed -S base-devel wget git
pause

# Video Driver Selection
vid=$(whiptail --title "Graphics Driver" --menu "Choose a graphics driver for your system" 15 60 4 \
    "xf86-video-intel" "Intel drivers" \
    "xf86-video-amdgpu" "AMD drivers" \
    "nvidia" "Nvidia drivers" \
    "Skip" "No drivers" 3>&1 1>&2 2>&3)

if [ "$vid" = "Skip" ]; then 
  vid="" 
else
  printf "${R}# Installing video driver: $vid ${NC}\n"
  sudo pacman --noconfirm --needed -S $vid
fi

pause

# Confirm installation of standard repo packages
PACKAGES=$(cat packagelist | sed 's/[ \t]*$//' | cut -d' ' -f1 | tr '\n' ' ')
PKG_PROMPT=$(printf "    - %s\n" $PACKAGES)
if whiptail --title "Packages from standard repo" --yesno "The following packages will be installed:\n$PKG_PROMPT\nWould you like to proceed?" 25 75; then
  sudo pacman -S --noconfirm --needed $PACKAGES
else
  echo "User canceled the package installation."
  exit 1
fi

pause
clear

# Install AUR packages
if ! command -v $HELPER &> /dev/null; then
  echo "It seems that you don't have $HELPER installed, installing it now..."
  git clone https://aur.archlinux.org/$HELPER.git ~/.srcs/$HELPER
  (cd ~/.srcs/$HELPER/ && makepkg -si )
fi

AUR_PACKS=$(cat packagelist-aur | sed 's/[ \t]*$//' | cut -d' ' -f1 | tr '\n' ' ')
$HELPER --quiet -S $AUR_PACKS

printf "${R} # All packages installed ${NC}\n"
pause
clear

# Shell selection using whiptail
if whiptail --title "Change Default Shell" --yesno "Would you like to use fish as your default shell?" 10 50; then
  chsh -s /usr/bin/fish
fi

if whiptail --title "Stow Dotfiles" --yesno "Would you like to stow the dotfiles in your home directory?" 10 50; then
  if [ -d "$HOME/dotfiles" ]; then
    stow -d "$HOME/dotfiles" -t "$HOME" *
    printf "${G}Dotfiles have been successfully stowed.${NC}\n"
  else
    printf "${R}The directory ~/dotfiles does not exist. Cannot stow dotfiles.${NC}\n"
  fi
else
  printf "${Y}Skipping stowing of dotfiles.${NC}\n"
fi

echo "Dotfiles installation complete!"
