palette = "catppuccin_frappe"

scan_timeout = 10
add_newline = false
format = "$directory $character"
right_format = "$cmd_duration"

[character]
success_symbol = "[ ](bold green)"
error_symbol = "[ ](bold red)"
vicmd_symbol = "[ ](bold yellow)"
vimcmd_replace_symbol = "[ ](bold red)"
vimcmd_replace_one_symbol = "[ ](bold red)"

[username]
show_always = true
style_user = "bold bg:none fg:blue"
format = "[$user]($style)"

[hostname]
disabled = true
ssh_only = false
style = "bold bg:none fg:text"
format = "@[$hostname]($style) "

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "./"
style = "bold lavender"

[git_branch]
format = " on [$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold mauve"

[time]
disabled = false
use_12hr = true
time_range = "-"
time_format = "%R"
utc_time_offset = "local"
format = "[ $time 󰥔]($style) "
style = "bold overlay2"

[cmd_duration]
min_time = 2000
show_milliseconds = false
format = "took [$duration]($style)"
style = "bold yellow"
disabled = false

[line_break]
disabled = false

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
