#!/bin/bash

check_bluetooth_state() {
  if ! systemctl is-active --quiet bluetooth; then
    echo 
  elif [ "$(bluetoothctl show | grep -c "Powered: yes")" -eq 0 ]; then
    echo "󰂯 "
  elif [ "$(bluetoothctl info | grep -c "Connected: yes")" -eq 0 ]; then
    echo "󰂯 "
  else
    echo "󰂱 "
  fi
}

check_bluetooth_state
