#!/bin/bash


# Function to fetch weather data
get_weather() {
    read latitude longitude < ~/location

    local font="$1"
    local color_day="$2"
    local color_night="$3"
    local url="https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code,is_day&forecast_days=1&daily=sunrise,sunset&timezone=GMT&timeformat=unixtime"


    weather_data=$(curl -s "$url" | jq '{
        temperature: .current.temperature_2m,
        weather_code: .current.weather_code,
        is_day: .current.is_day,
        sunrise: .daily.sunrise[0],
        sunset: .daily.sunset[0]
    }')

    
    temperature=$(echo "$weather_data" | jq -r '.temperature')
    weather_code=$(echo "$weather_data" | jq -r '.weather_code')
    is_day=$(echo "$weather_data" | jq -r '.is_day')

    if [[ "$is_day" -eq "1" ]]; then
      weather_type=$(echo "$weather_code" | jq -r '
          if . == 0 then ""
          elif . >= 1 and . <= 3 then ""
          elif . == 45 or . == 48 then ""
          elif . >= 51 and . <= 55 then ""
          elif . >= 61 and . <= 65 then ""
          elif . >= 71 and . <= 75 then ""
          elif . == 77 then ""
          elif . >= 80 and . <= 82 then ""
          elif . == 85 or . == 86 then ""
          elif . == 95 then ""
          elif . == 96 or . == 99 then ""
          else "Unknown"
          end
      ')
      echo "%{F${color_day}}%{T${font}}$weather_type %{T-}%{F-} ${temperature}°C"
    else 
      weather_type=$(echo "$weather_code" | jq -r '
          if . == 0 then ""
          elif . >= 1 and . <= 3 then ""
          elif . == 45 or . == 48 then ""
          elif . >= 51 and . <= 55 then ""
          elif . >= 61 and . <= 65 then ""
          elif . >= 71 and . <= 75 then ""
          elif . == 77 then ""
          elif . >= 80 and . <= 82 then ""
          elif . == 85 or . == 86 then ""
          elif . == 95 then ""
          elif . == 96 or . == 99 then ""
          else "Unknown"
          end
      ')
      echo "%{F${color_night}}%{T${font}}$weather_type %{T-}%{F-} ${temperature}°C"
    fi
    
    # Print the result
}

get_weather "$1" "$2" "$3"
